version: '2'
services:
  # --------------------------------------------------------------------------
  # Caddy
  # --------------------------------------------------------------------------
  caddy:
    image: abiosoft/caddy:latest
    restart: unless-stopped
    hostname: caddy
    env_file: .env
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./codalab/static:/var/www/codalab/static
      - ./certs/caddy:/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "200k"
