name: Run Pytests
on: [pull_request]
env:
  DJANGO_SETTINGS_MODULE: "codalab.settings.local"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "codalab_website"
  DB_USER: "root"
  DB_PASSWORD: "password"
  DJANGO_CONFIGURATION: "Test"
  CHAHUB_API_URL: "http://localhost/test/"
  CHAHUB_API_KEY: "some-secret-key"
jobs:
  run-tests:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        # use the same version as docker-compose.yml
        image: "postgres:12.6-alpine"
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: codalab_website
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          sudo apt-get update --allow-releaseinfo-change && sudo apt-get install libmemcached-dev --fix-missing
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r ./app/requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --show-source
      - name: Run Tests
        run: |
          py.test
        working-directory: ./codalab
